# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define the jobs we want to run for this project
jobs:
  build-and-test-express-js:
    docker:
      - image: cimg/node:16.13.0 # latest stable node at the time of writing
        # auth:
        #   username: mydockerhub-user
        #   password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run: echo "this is the build and test express.js job"
      - run: |
          cd back-end
          pwd # for debugging: show current working directory
          ls # for debugging: show sub-directories in here
      - run: |
          cd back-end
          npm install # install all dependencies listed in package.json
          npm test # run all unit tests

  build-react-js:
    docker:
      - image: cimg/node:16.13.0 # latest stable node at the time of writing
        
    steps:
      - checkout
      - run: echo "this is the build react.js job"
      - run: |
          cd back-end
          pwd # for debugging: show current working directory
          ls # for debugging: show sub-directories in here
      - run: |
          cd front-end
          npm install # install all dependencies listed in package.json
          npm run build # have react build the stand-alone front-end code
  
  # Build & push Docker image
  pull-build-push:
    docker:
      - image: cimg/node:16.13.0
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASS  # context / project UI env-var reference
    steps:
      - checkout
      - setup_remote_docker
      - run: echo "we're pulling, building, and pushing the docker images!"

      # pull build and push docker
      - run: |
          cd back-end
          docker pull seungguini/potluck-backend
          docker build --platform linux/amd64 -t seungguini/potluck-backend .
          echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
          docker push seungguini/potluck-backend

      - run: |
          cd front-end
          docker pull seungguini/potluck-frontend
          docker build --platform linux/amd6 -t seungguini/potluck-frontend .
          echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
          docker push seungguini/potluck-frontend
      

  # Pull & build docker on server
  deploy:
    docker:
      - image: cimg/node:16.13.0
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASS  # context / project UI env-var reference
    steps:
      - checkout   
      - setup_remote_docker
      - run: ssh -oStrictHostKeyChecking=no -v $USER@$IP 
      - run: echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
      - run: "./deploy.sh"
      

# Orchestrate our job run sequence
workflows:
  build-and-test-back-end:
    jobs:
      - build-and-test-express-js
  build-front-end:
    jobs:
      - build-react-js
  build-push-deploy-docker:
    jobs:
      - pull-build-push:
          filters:
            branches:
              only:
                - master
                - docker-Implementation
      - deploy:
          requires:
            - pull-build-push # run this job only when docker has been built and pushed onto Dockerhub
          filters:
            branches:
              only:
                - master
                - docker-Implementation